### ISSUE TITLE
some work on Arabic-Indic Numerals 

### ISSUE THREAD

**Issue by claybiockiller** [fasttime/JScrewIt#24]
if you use most valid Arabic variant as locale Parameters of Number.prototype.toLocaleString(), the output will be Arabic-Indic Numerals. usinglocale Parameters string for Arabic which have shorter code(the one with shortest generated code is all lower case version of Arabic(Saudi Arabia), ie. "ar-sa")can shorten generated code for single Arabic-Indic Numerals character. it works in new browsers and Node.JS 12+.
for example:
in all new browsers:
"١":2867 (current method)
(1).toLocaleString("ar-sa"):2764 (since converted via web, whether "String" optimized is unknown)
but converted length of code using Number.prototype.toLocaleString() is still longer than escape sequence it self(for"١", escaping sequence is "\\u0661", which converted length is 1256 chars), so that method may not fit for strings escaped altogether.

**Comment by fasttime** [comment]
Thanks! This has been implemented in e476d9d and will be released with JScrewIt 2.21.

The new encoding affects Arabic and Persian digits along with a few more related characters, and is available in all new browsers as well as in IE 11, Safari 10+, Android Browser 4.4, and Node.js 13+. Node.js 12 is not included since it does not recognize locale arguments passed to `toLocaleString`.

The locale used for Arabic characters is "ar-td" in Chrome, Edge and Opera, and "ar" in other engines; the locale for Persian characters is always "fa".

By now, no multicharacter optimization exists, and so "١٠" is encoded as `1..toLocaleString("ar")+0..toLocaleString("ar")` rather than `10..toLocaleString("ar")`. This kind of optimization may be added in the future.

**Comment by Clayblockunova** [comment]
oh, I forgot NaN can also have localized name. the Russian string of NaN, "не число", may also helpful in shortening generated code, since currently "н" is 2857 chars, and (+[false]).toLocaleString("ru")[0] is 2594 chars.

**Comment by fasttime** [comment]
Those are not implemented yet because of various incompatibilities with IE 11. Expect them to be added in a later version under additional features.

**Comment by Clayblockunova** [comment]
sorry for bother you again. for those Latin-1 chars, you used padding blocks to avoid using numbers ended with digit between 4-9, but didn't use such a trick on those localized NaN related chars. is there any dificulty?

**Comment by fasttime** [comment]
You are right, those expressions should be padded.

**Comment by fasttime** [comment]
Implemented in JScrewIt 2.32.0.

**Comment by Clayblockunova** [comment]
Sorry for bother you again. For those number systems which isn't default of any language, use "fa-u-nu-" with number system code as parameter of `Number.prototype.toLocaleString()` can return string in that number system (Persian have shortest code in languages support this trick). But that's only practical in batch conversion because "౧" (Telugu 1) costs 2241 chars in current method but `1..toLocaleString("fa-u-nu-telu")` cost 2512 chars.

**Comment by fasttime** [comment]
What other number systems other than "-telu" would work here?

**Comment by Clayblockunova** [comment]
theoretically, "adlm", "ahom", "arab", "arabext", "bali", "beng", "bhks", "brah", "cakm", "cham", "deva", "diak", "fullwide", "gong", "gonm", "gujr", "guru", "hanidec", "hmng", "hmnp", "java", "kali", "khmr", "knda", "lana", "lanatham", "laoo", "latn", "lepc", "limb", "mathbold", "mathdbl", "mathmono", "mathsanb", "mathsans", "mlym", "modi", "mong", "mroo", "mtei", "mymr", "mymrshan", "mymrtlng", "newa", "nkoo", "olck", "orya", "osma", "rohg", "saur", "segment", "shrd", "sind", "sinh", "sora", "sund", "takr", "talu", "tamldec", "telu", "thai", "tibt", "tirh", "vaii", "wara", "wcho" would be supported. But, "arab", "arabext", "beng" and "latn" are useless. The former 3 respectively are default of "ar-td", "fa" and “bn”, and "latn" is just common western Arabic numbers which can easily get by our basic trick.
