### ISSUE TITLE
Something about `document.createElement()`

### ISSUE THREAD

**Issue by Clayblockunova** [fasttime/JScrewIt#38]
Currently, there is a definition of "V" relies on `document.createElement()` would be active with `ANY_DOCUMENT` and supposed to work in Android Webview 4.0-4.3, but MDN says `document.createElement()` was added in Android Webview 4.4. should we make an independent feature for `document.createElement()`?
Additionally, `[]+document.createElement(false)` will return "[object HTMLUnknownElement]" in most browsers, which would be useful for leters "M" and "L". but IDK how `document.createElement(false)` work in Android Webview 4.0-4.3 and would that be useful for letter "U".

**Comment by fasttime** [comment]
I did some testing in Android Browser < 4.4, and the definition of `"V"` you mentioned does work well, while `[]+document.createElement(false)` evaluates to `"[object HTMLElement]"`. It is possible that `createElement` is an addition of the browser itself, rather than being provided by the WebView component, and that would explain the differences in behavior with Android Browser 4.4.

**Comment by Clayblockunova** [comment]
Added new definitions in PR.

**Comment by fasttime** [comment]
The new definitions are now included in JScrewIt 2.35.0.
